MVCClientConnector/Controllers/ConnectorController.cs
using MVCClientConnector.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCClientConnector.Controllers
{
    public class ConnectorController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Index(int Id,string Ky)
        {
            ClientConnectorService svc = new ClientConnectorService(Id,Ky);
            int newVal = 0;
            svc.ReadNext(null, out newVal);
            ViewBag.CId = Id;
            ViewBag.secK = Ky;
            ViewBag.newVal = newVal;

            return Index();
        }
    }
}

MVCClientConnector/Controllers/JConnectorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCClientConnector.Controllers
{
    public class JConnectorController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Test()
        {
            return View();
        }

        public ActionResult TestIntString()
        {
            return View();
        }

        public ActionResult TestIntBlob(int? id)
        {
            return View();
        }
    }
}

MVCClientConnector/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My Datwendo ClientConnector MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Datwendo", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("C# Server Test", "Index", "Connector")</li>                            
                            <li>@Html.ActionLink("Jscript Test", "Test", "JConnector")</li>
                            <li>@Html.ActionLink("Jscript Test Data", "TestIntString", "JConnector")</li>
                            <li>@Html.ActionLink("Jscript Test Blob", "TestIntBlob", "JConnector")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My Datwendo .NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>